const lowerCaseKeys = [
  [
    {name: 'Backquote', value: '`'},
    {name: 'Digit1', value: '1'},
    {name: 'Digit2', value: '2'},
    {name: 'Digit3', value: '3'},
    {name: 'Digit4', value: '4'},
    {name: 'Digit5', value: '5'},
    {name: 'Digit6', value: '6'},
    {name: 'Digit7', value: '7'},
    {name: 'Digit8', value: '8'},
    {name: 'Digit9', value: '9'},
    {name: 'Digit0', value: '0'},
    {name: 'Minus', value: '-'},
    {name: 'Equal', value: '='},
    {name: 'Backspace', value: 'Back'},
  ],
  [
    {name: 'Tab', value: 'Tab'},
    {name: 'KeyQ', value: 'q'},
    {name: 'KeyW', value: 'w'},
    {name: 'KeyE', value: 'e'},
    {name: 'KeyR', value: 'r'},
    {name: 'KeyT', value: 't'},
    {name: 'KeyY', value: 'y'},
    {name: 'KeyU', value: 'u'},
    {name: 'KeyI', value: 'i'},
    {name: 'KeyO', value: 'o'},
    {name: 'KeyP', value: 'p'},
    {name: 'BracketLeft', value: '['},
    {name: 'BracketRight', value: ']'},
    {name: 'Backslash', value: '\\'},
  ],
  [
    {name: 'CapsLock', value: 'Caps Lock'},
    {name: 'KeyA', value: 'a'},
    {name: 'KeyS', value: 's'},
    {name: 'KeyD', value: 'd'},
    {name: 'KeyF', value: 'f'},
    {name: 'KeyG', value: 'g'},
    {name: 'KeyH', value: 'h'},
    {name: 'KeyJ', value: 'j'},
    {name: 'KeyK', value: 'k'},
    {name: 'KeyL', value: 'l'},
    {name: 'Semicolon', value: ';'},
    {name: 'Quote', value: '\''},
    {name: 'Enter', value: 'Enter'},
  ],
  [
    {name: 'ShiftLeft', value: 'Shift'},
    {name: 'KeyZ', value: 'z'},
    {name: 'KeyX', value: 'x'},
    {name: 'KeyC', value: 'c'},
    {name: 'KeyV', value: 'v'},
    {name: 'KeyB', value: 'b'},
    {name: 'KeyN', value: 'n'},
    {name: 'KeyM', value: 'm'},
    {name: 'Comma', value: ','},
    {name: 'Period', value: '.'},
    {name: 'Slash', value: '/'},
    {name: 'ShiftRight', value: 'Shift'},
  ],
  [
    {name: 'Dotcom', value: '.com'},
    {name: 'At', value: '@'},
    {name: 'Space', value: 'Space'},
  ],
];

const upperCaseKeys = [
  [
    {name: 'Backquote', value: '~'},
    {name: 'Digit1', value: '!'},
    {name: 'Digit2', value: '@'},
    {name: 'Digit3', value: '#'},
    {name: 'Digit4', value: '$'},
    {name: 'Digit5', value: '%'},
    {name: 'Digit6', value: '^'},
    {name: 'Digit7', value: '&'},
    {name: 'Digit8', value: '*'},
    {name: 'Digit9', value: '('},
    {name: 'Digit0', value: ')'},
    {name: 'Minus', value: '_'},
    {name: 'Equal', value: '+'},
    {name: 'Backspace', value: 'Back'},
  ],
  [
    {name: 'Tab', value: 'Tab'},
    {name: 'KeyQ', value: 'Q'},
    {name: 'KeyW', value: 'W'},
    {name: 'KeyE', value: 'E'},
    {name: 'KeyR', value: 'R'},
    {name: 'KeyT', value: 'T'},
    {name: 'KeyY', value: 'Y'},
    {name: 'KeyU', value: 'U'},
    {name: 'KeyI', value: 'I'},
    {name: 'KeyO', value: 'O'},
    {name: 'KeyP', value: 'P'},
    {name: 'BracketLeft', value: '{'},
    {name: 'BracketRight', value: '}'},
    {name: 'Backslash', value: '|'},
  ],
  [
    {name: 'CapsLock', value: 'Caps Lock'},
    {name: 'KeyA', value: 'A'},
    {name: 'KeyS', value: 'S'},
    {name: 'KeyD', value: 'D'},
    {name: 'KeyF', value: 'F'},
    {name: 'KeyG', value: 'G'},
    {name: 'KeyH', value: 'H'},
    {name: 'KeyJ', value: 'J'},
    {name: 'KeyK', value: 'K'},
    {name: 'KeyL', value: 'L'},
    {name: 'Semicolon', value: ':'},
    {name: 'Quote', value: '"'},
    {name: 'Enter', value: 'Enter'},
  ],
  [
    {name: 'ShiftLeft', value: 'Shift'},
    {name: 'KeyZ', value: 'Z'},
    {name: 'KeyX', value: 'X'},
    {name: 'KeyC', value: 'C'},
    {name: 'KeyV', value: 'V'},
    {name: 'KeyB', value: 'B'},
    {name: 'KeyN', value: 'N'},
    {name: 'KeyM', value: 'M'},
    {name: 'Comma', value: '<'},
    {name: 'Period', value: '>'},
    {name: 'Slash', value: '?'},
    {name: 'ShiftRight', value: 'Shift'},
  ],
  [
    {name: 'Dotcom', value: '.com'},
    {name: 'At', value: '@'},
    {name: 'Space', value: 'Space'},
  ],
]

export {lowerCaseKeys, upperCaseKeys};